-- ============================================================
-- MACROÉCONOMIE 3 — SCRIPT MAÎTRE SUPABASE
-- VERSION COMPLÈTE — CODE APOGÉE
-- À EXÉCUTER EN UNE SEULE FOIS
-- ============================================================
-- IMPORTANT : ce script ne supprime ni les étudiants, ni les
-- séances, ni les présences déjà enregistrés. Il remplace les
-- fonctions de l'ancienne version et ajoute le Code Apogée.
-- ============================================================

create extension if not exists pgcrypto;

-- ============================================================
-- 1. TABLES DE BASE
-- ============================================================

create table if not exists public.professors (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    student_identifier varchar not null,
    nom varchar not null,
    prenom varchar not null,
    parcours varchar not null,
    created_at timestamptz not null default now()
);

create table if not exists public.sessions (
    id bigint generated by default as identity primary key,
    course_name varchar not null default 'Macroéconomie 3',
    session_date date not null,
    start_time timestamptz not null,
    end_time timestamptz not null,
    qr_token uuid not null default gen_random_uuid(),
    confirmation_code varchar(3) not null,
    status varchar not null default 'PROGRAMMEE',
    created_at timestamptz not null default now()
);

create table if not exists public.attendances (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    session_id bigint not null references public.sessions(id) on delete cascade,
    validated_at timestamptz not null default now()
);

alter table public.professors enable row level security;
alter table public.students enable row level security;
alter table public.sessions enable row level security;
alter table public.attendances enable row level security;

-- ============================================================
-- 2. PROFESSEUR
-- ============================================================

insert into public.professors (user_id)
select id
from auth.users
where id = (
    select id from auth.users order by created_at asc limit 1
)
on conflict (user_id) do nothing;

-- Les nouveaux comptes Supabase authentifiés peuvent également
-- accéder à l'espace professeur.
-- La table professors est conservée pour compatibilité.

-- ============================================================
-- 3. COMPATIBILITÉ ANCIENNE BASE
-- ============================================================

alter table public.students
    add column if not exists student_identifier varchar;

alter table public.students
    add column if not exists nom varchar;

alter table public.students
    add column if not exists prenom varchar;

alter table public.students
    add column if not exists parcours varchar;

alter table public.students
    add column if not exists created_at timestamptz default now();

alter table public.sessions
    add column if not exists course_name varchar default 'Macroéconomie 3';

alter table public.sessions
    add column if not exists session_date date;

alter table public.sessions
    add column if not exists start_time timestamptz;

alter table public.sessions
    add column if not exists end_time timestamptz;

alter table public.sessions
    add column if not exists qr_token uuid default gen_random_uuid();

alter table public.sessions
    add column if not exists confirmation_code varchar(3);

alter table public.sessions
    add column if not exists status varchar default 'PROGRAMMEE';

alter table public.sessions
    add column if not exists created_at timestamptz default now();

alter table public.attendances
    add column if not exists student_id bigint;

alter table public.attendances
    add column if not exists session_id bigint;

alter table public.attendances
    add column if not exists validated_at timestamptz default now();

-- Les anciennes données restent en place.
-- Pour une ancienne base, les colonnes déjà remplies
-- ne sont pas écrasées.

-- ============================================================
-- 4. CONTRAINTES / INDEX
-- ============================================================

create unique index if not exists students_student_identifier_key
on public.students(student_identifier);

create unique index if not exists sessions_qr_token_key
on public.sessions(qr_token);

create unique index if not exists attendances_student_session_key
on public.attendances(student_id, session_id);

create unique index if not exists one_active_session_only
on public.sessions(status)
where status = 'ACTIVE';

create index if not exists idx_students_parcours
on public.students(parcours);

create index if not exists idx_sessions_status
on public.sessions(status);

create index if not exists idx_sessions_start_time
on public.sessions(start_time);

create index if not exists idx_attendances_student
on public.attendances(student_id);

create index if not exists idx_attendances_session
on public.attendances(session_id);

-- ============================================================
-- 5. SÉQUENCE ANCIENNE — CONSERVÉE POUR COMPATIBILITÉ
-- ============================================================

create sequence if not exists public.student_identifier_seq
    start with 101
    increment by 1
    minvalue 101;

-- Elle n'est plus utilisée pour les nouveaux étudiants :
-- le Code Apogée est maintenant saisi par le professeur.

-- ============================================================
-- 6. CONTRAINTES PARCOURS / STATUT
-- ============================================================

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'students_parcours_check'
          and conrelid = 'public.students'::regclass
    ) then
        alter table public.students
        add constraint students_parcours_check
        check (
            parcours in (
                'Analyse économique',
                'Économétrie appliquée'
            )
        );
    end if;
exception when others then
    null;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'sessions_status_check'
          and conrelid = 'public.sessions'::regclass
    ) then
        alter table public.sessions
        add constraint sessions_status_check
        check (
            status in (
                'PROGRAMMEE',
                'ACTIVE',
                'FERMEE',
                'EXPIREE'
            )
        );
    end if;
exception when others then
    null;
end $$;

-- ============================================================
-- 7. SAVOIR SI L'UTILISATEUR EST PROFESSEUR
-- ============================================================

create or replace function public.is_professor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select auth.uid() is not null;
$$;

-- ============================================================
-- 8. INSCRIPTION ÉTUDIANT — CODE APOGÉE
-- ============================================================

drop function if exists public.register_student(varchar, varchar, varchar);

create or replace function public.register_student(
    p_nom varchar,
    p_prenom varchar,
    p_code_apogee varchar,
    p_parcours varchar
)
returns public.students
language plpgsql
security definer
set search_path = public
as $$
declare
    v_student public.students%rowtype;
    v_code varchar;
begin
    if not public.is_professor() then
        raise exception 'Accès réservé au professeur.';
    end if;

    if trim(coalesce(p_nom, '')) = '' then
        raise exception 'Le nom est obligatoire.';
    end if;

    if trim(coalesce(p_prenom, '')) = '' then
        raise exception 'Le prénom est obligatoire.';
    end if;

    v_code := upper(trim(coalesce(p_code_apogee, '')));

    if v_code = '' then
        raise exception 'Le Code Apogée est obligatoire.';
    end if;

    if p_parcours not in (
        'Analyse économique',
        'Économétrie appliquée'
    ) then
        raise exception 'Parcours invalide.';
    end if;

    insert into public.students (
        student_identifier,
        nom,
        prenom,
        parcours
    )
    values (
        v_code,
        trim(p_nom),
        trim(p_prenom),
        p_parcours
    )
    returning * into v_student;

    return v_student;

exception
    when unique_violation then
        raise exception 'Ce Code Apogée existe déjà.';
end;
$$;

-- ============================================================
-- 9. RECHERCHER UN ÉTUDIANT PAR CODE APOGÉE
-- ============================================================

create or replace function public.get_student_by_identifier(
    p_identifier varchar
)
returns table (
    id bigint,
    student_identifier varchar,
    nom varchar,
    prenom varchar,
    parcours varchar
)
language sql
security definer
set search_path = public
as $$
    select
        s.id,
        s.student_identifier,
        s.nom,
        s.prenom,
        s.parcours
    from public.students s
    where upper(s.student_identifier) = upper(trim(p_identifier))
    limit 1;
$$;

-- ============================================================
-- 10. OUVRIR UNE SÉANCE
-- ============================================================

create or replace function public.open_session(
    p_duration_minutes integer default 120
)
returns public.sessions
language plpgsql
security definer
set search_path = public
as $$
declare
    v_session public.sessions%rowtype;
    v_code varchar(3);
    v_now timestamptz := now();
begin
    if not public.is_professor() then
        raise exception 'Accès réservé au professeur.';
    end if;

    if p_duration_minutes < 5 or p_duration_minutes > 360 then
        raise exception 'La durée doit être comprise entre 5 et 360 minutes.';
    end if;

    update public.sessions
    set status = 'EXPIREE'
    where status = 'ACTIVE'
      and end_time <= v_now;

    if exists (
        select 1
        from public.sessions
        where status = 'ACTIVE'
    ) then
        raise exception 'Une séance est déjà active.';
    end if;

    select string_agg(
        substr(
            'ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
            floor(random() * 32 + 1)::integer,
            1
        ),
        ''
    )
    into v_code
    from generate_series(1, 3);

    insert into public.sessions (
        course_name,
        session_date,
        start_time,
        end_time,
        confirmation_code,
        status
    )
    values (
        'Macroéconomie 3',
        (v_now at time zone 'Africa/Casablanca')::date,
        v_now,
        v_now + make_interval(mins => p_duration_minutes),
        v_code,
        'ACTIVE'
    )
    returning * into v_session;

    return v_session;
end;
$$;

-- ============================================================
-- 11. FERMER MANUELLEMENT UNE SÉANCE
-- ============================================================

create or replace function public.close_session(
    p_session_id bigint
)
returns public.sessions
language plpgsql
security definer
set search_path = public
as $$
declare
    v_session public.sessions%rowtype;
begin
    if not public.is_professor() then
        raise exception 'Accès réservé au professeur.';
    end if;

    update public.sessions
    set status = 'FERMEE'
    where id = p_session_id
      and status = 'ACTIVE'
    returning * into v_session;

    if not found then
        raise exception 'Séance introuvable ou déjà fermée.';
    end if;

    return v_session;
end;
$$;

-- ============================================================
-- 12. EXPIRER LES SÉANCES TERMINÉES
-- ============================================================

create or replace function public.expire_sessions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    v_count integer;
begin
    update public.sessions
    set status = 'EXPIREE'
    where status = 'ACTIVE'
      and end_time <= now();

    get diagnostics v_count = row_count;

    return v_count;
end;
$$;

-- ============================================================
-- 13. RÉCUPÉRER UNE SÉANCE DEPUIS LE QR
-- ============================================================

create or replace function public.get_session_by_qr_token(
    p_qr_token uuid
)
returns table (
    id bigint,
    course_name varchar,
    session_date date,
    start_time timestamptz,
    end_time timestamptz,
    qr_token uuid,
    status varchar
)
language plpgsql
security definer
set search_path = public
as $$
begin
    perform public.expire_sessions();

    return query
    select
        s.id,
        s.course_name,
        s.session_date,
        s.start_time,
        s.end_time,
        s.qr_token,
        s.status
    from public.sessions s
    where s.qr_token = p_qr_token
      and s.status = 'ACTIVE'
      and now() >= s.start_time
      and now() < s.end_time
    limit 1;
end;
$$;

-- ============================================================
-- 14. VALIDER UNE PRÉSENCE — CODE APOGÉE
-- ============================================================

create or replace function public.validate_attendance(
    p_identifier varchar,
    p_qr_token uuid,
    p_confirmation_code varchar
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_student public.students%rowtype;
    v_session public.sessions%rowtype;
begin
    select *
    into v_student
    from public.students
    where upper(student_identifier) = upper(trim(p_identifier))
    limit 1;

    if not found then
        return json_build_object(
            'success', false,
            'message', 'Code Apogée introuvable.'
        );
    end if;

    select *
    into v_session
    from public.sessions
    where qr_token = p_qr_token
    limit 1;

    if not found then
        return json_build_object(
            'success', false,
            'message', 'QR code invalide ou inconnu.'
        );
    end if;

    if now() < v_session.start_time then
        return json_build_object(
            'success', false,
            'message', 'La séance n''est pas encore ouverte.'
        );
    end if;

    if now() >= v_session.end_time then

        update public.sessions
        set status = 'EXPIREE'
        where id = v_session.id
          and status = 'ACTIVE';

        return json_build_object(
            'success', false,
            'message', 'Cette séance est terminée.'
        );
    end if;

    if v_session.status <> 'ACTIVE' then
        return json_build_object(
            'success', false,
            'message', 'Cette séance n''est plus active.'
        );
    end if;

    if coalesce(upper(trim(p_confirmation_code)), '')
       <> upper(trim(v_session.confirmation_code)) then

        return json_build_object(
            'success', false,
            'message', 'Code de confirmation incorrect.'
        );
    end if;

    if exists (
        select 1
        from public.attendances a
        where a.student_id = v_student.id
          and a.session_id = v_session.id
    ) then
        return json_build_object(
            'success', false,
            'message', 'Présence déjà enregistrée pour cette séance.'
        );
    end if;

    begin

        insert into public.attendances (
            student_id,
            session_id,
            validated_at
        )
        values (
            v_student.id,
            v_session.id,
            now()
        );

    exception
        when unique_violation then
            return json_build_object(
                'success', false,
                'message', 'Présence déjà enregistrée pour cette séance.'
            );
    end;

    return json_build_object(
        'success', true,
        'message', 'Présence enregistrée avec succès.',
        'student_identifier', v_student.student_identifier,
        'nom', v_student.nom,
        'prenom', v_student.prenom,
        'parcours', v_student.parcours,
        'validated_at', now()
    );
end;
$$;

-- ============================================================
-- 15. EMPÊCHER LA MODIFICATION DU CODE APOGÉE
-- ============================================================

create or replace function public.prevent_student_identifier_change()
returns trigger
language plpgsql
as $$
begin
    if new.student_identifier is distinct from old.student_identifier then
        raise exception 'Le Code Apogée ne peut pas être modifié.';
    end if;

    return new;
end;
$$;

drop trigger if exists protect_student_identifier
on public.students;

drop trigger if exists trg_prevent_student_identifier_change
on public.students;

create trigger protect_student_identifier
before update on public.students
for each row
execute function public.prevent_student_identifier_change();

-- ============================================================
-- 16. POLITIQUES RLS
-- ============================================================

drop policy if exists professors_select_policy
on public.professors;

create policy professors_select_policy
on public.professors
for select
to authenticated
using (user_id = auth.uid());

-- Supprimer les anciennes variantes connues.

drop policy if exists authenticated_students_all
on public.students;

drop policy if exists authenticated_sessions_all
on public.sessions;

drop policy if exists authenticated_attendances_all
on public.attendances;

drop policy if exists professors_students_all
on public.students;

drop policy if exists professors_sessions_all
on public.sessions;

drop policy if exists professors_attendances_all
on public.attendances;

create policy professors_students_all
on public.students
for all
to authenticated
using (public.is_professor())
with check (public.is_professor());

create policy professors_sessions_all
on public.sessions
for all
to authenticated
using (public.is_professor())
with check (public.is_professor());

create policy professors_attendances_all
on public.attendances
for all
to authenticated
using (public.is_professor())
with check (public.is_professor());

-- ============================================================
-- 17. DROITS
-- ============================================================

revoke all on table public.professors
from anon, authenticated;

revoke all on table public.students
from anon;

revoke all on table public.sessions
from anon;

revoke all on table public.attendances
from anon;

grant select on public.professors
to authenticated;

grant select, insert, update, delete
on public.students
to authenticated;

grant select, insert, update, delete
on public.sessions
to authenticated;

grant select, insert, update, delete
on public.attendances
to authenticated;

revoke all on function public.is_professor()
from public;

revoke all on function public.register_student(
    varchar,
    varchar,
    varchar,
    varchar
)
from public;

revoke all on function public.get_student_by_identifier(
    varchar
)
from public;

revoke all on function public.open_session(
    integer
)
from public;

revoke all on function public.close_session(
    bigint
)
from public;

revoke all on function public.expire_sessions()
from public;

revoke all on function public.get_session_by_qr_token(
    uuid
)
from public;

revoke all on function public.validate_attendance(
    varchar,
    uuid,
    varchar
)
from public;

grant execute on function public.is_professor()
to authenticated;

grant execute on function public.register_student(
    varchar,
    varchar,
    varchar,
    varchar
)
to authenticated;

grant execute on function public.get_student_by_identifier(
    varchar
)
to anon, authenticated;

grant execute on function public.open_session(
    integer
)
to authenticated;

grant execute on function public.close_session(
    bigint
)
to authenticated;

grant execute on function public.expire_sessions()
to anon, authenticated;

grant execute on function public.get_session_by_qr_token(
    uuid
)
to anon, authenticated;

grant execute on function public.validate_attendance(
    varchar,
    uuid,
    varchar
)
to anon, authenticated;

-- ============================================================
-- 18. VÉRIFICATION FINALE
-- ============================================================

select
    (select count(*) from public.students) as nombre_etudiants,
    (select count(*) from public.sessions) as nombre_seances,
    (select count(*) from public.attendances) as nombre_presences,
    (select count(*) from public.professors) as nombre_professeurs;

-- ============================================================
-- FIN DU SCRIPT MAÎTRE
-- ============================================================